cadc-tap-postgres:
  fullnameOverride: "obstap"

  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "rubin-data-dev.slac.stanford.edu"
  vaultSecretsPath: "secret/rubin/usdf-staffrsp-dev/tap"

  config:
    gcsBucket: "async-results.lsst.codes"
    gcsBucketUrl: "http://async-results.lsst.codes"

pull-secret:
  enabled: true
  path: secret/rubin/usdf-staffrsp-dev/pull-secret
