cadc-tap-postgres:
  pull_secret: 'pull-secret'
  tag: "1.0"
  host: "rubin-data-dev.slac.stanford.edu"

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/rubin/rubin-data-dev.slac.stanford.edu/tap'

  gcs_bucket: 'async-results.lsst.codes'
  gcs_bucket_url: 'http://async-results.lsst.codes'

pull-secret:
  enabled: true
  path: secret/rubin/rubin-data-dev.slac.stanford.edu/pull-secret
