environment: base
fqdn: base-lsp.lsst.codes
vault_path_prefix: secret/k8s_operator/base-lsp.lsst.codes

alert_stream_broker:
  enabled: false
cachemachine:
  enabled: true
cert_manager:
  enabled: true
datalinker:
  enabled: false
exposurelog:
  enabled: true
gafaelfawr:
  enabled: true
hips:
  enabled: false
ingress_nginx:
  enabled: true
mobu:
  enabled: false
moneypenny:
  enabled: true
narrativelog:
  enabled: true
noteburst:
  enabled: false
nublado2:
  enabled: true
plot_navigator:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
sasquatch:
  enabled: false
production_tools:
  enabled: false
semaphore:
  enabled: false
squareone:
  enabled: true
squash_api:
  enabled: false
strimzi:
  enabled: false
strimzi_registry_operator:
  enabled: false
tap:
  enabled: false
tap_schema:
  enabled: false
telegraf:
  enabled: true
telegraf-ds:
  enabled: true
times_square:
  enabled: false
vault_secrets_operator:
  enabled: true
vo_cutouts:
  enabled: false
