apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "datalinker.fullname" . }}-butler-secret
  labels:
    {{- include "datalinker.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/butler-secret"
  type: Opaque
