kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nublado2.fullname" . }}-hub
subjects:
  # Note: this service account is created by the jupyterhub subchart
  - kind: ServiceAccount
    name: hub
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "nublado2.fullname" . }}-hub
  apiGroup: rbac.authorization.k8s.io
