kind: ConfigMap
apiVersion: v1
metadata:
  name: nublado-config
  labels:
    {{- include "nublado2.labels" . | nindent 4 }}
data:
  nublado_config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
