apiVersion: v1
kind: Service
metadata:
  name: {{ template "gafaelfawr.fullname" . }}-redis
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: "TCP"
      targetPort: 6379
  selector:
    {{- include "gafaelfawr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "redis"
  sessionAffinity: None
