{{- if .Values.cloudsql.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gafaelfawr.fullname" . }}
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.cloudsql.enabled }}
    iam.gke.io/gcp-service-account: {{ required "cloudsql.serviceAccount must be set to a valid Google service account" .Values.cloudsql.serviceAccount | quote }}
    {{- end }}
{{- end }}
