apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moneypenny.fullname" . }}-m-config
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
data:
  m.yaml: |
    {{- toYaml .Values.orders | nindent 4 }}
