apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moneypenny.fullname" . }}-quips
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
data:
  quips.txt: |
    {{- .Values.quips | nindent 4 }}
