apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moneypenny.fullname" .}}
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
data:
  SAFIR_NAME: "moneypenny"
  SAFIR_PROFILE: "production"
  SAFIR_LOGGER: "moneypenny"
  SAFIR_LOG_LEVEL: "INFO"
  DOCKER_SECRET_NAME: "pull-secret"
