apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "moneypenny.fullname" . }}
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "moneypenny.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config-m: {{ include (print $.Template.BasePath "/cm-m-config.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "moneypenny.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: "pull-secret"
      serviceAccountName: {{ include "moneypenny.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: "moneypenny"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ template "moneypenny.fullname" . }}
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: "/"
              port: "http"
          readinessProbe:
            httpGet:
              path: "/"
              port: "http"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "m-config"
              mountPath: "/opt/lsst/software/moneypenny/config/M"
              readOnly: true
            - name: "quips"
              mountPath: "/opt/lsst/software/moneypenny/config/quips"
              readOnly: true
            - name: "podinfo"
              mountPath: "/etc/podinfo"
              readOnly: true
      volumes:
        - name: "m-config"
          configMap:
            name: {{ template "moneypenny.fullname" . }}-m-config
        - name: "quips"
          configMap:
            name: {{ template "moneypenny.fullname" . }}-quips
        - name: "podinfo"
          downwardAPI:
            items:
              - path: "name"
                fieldRef:
                  fieldPath: "metadata.name"
              - path: "uid"
                fieldRef:
                  fieldPath: "metadata.uid"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
