kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "moneypenny.serviceAccountName" . }}
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "moneypenny.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "moneypenny.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
