apiVersion: v1
kind: Service
metadata:
  name: {{ include "moneypenny.fullname" . }}
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 8080
      targetPort: "http"
  selector:
    {{- include "moneypenny.selectorLabels" . | nindent 4 }}
