orders:
  commission:
    - name: initcommission
      image: lsstsqre/inituserhome
      securityContext:
        runAsUser: 0
        runAsNonRootUser: false
      volumeMounts:
        - mountPath: /homedirs
          name: homedirs
  volumes:
    - name: homedirs
      nfs:
        server: ddn-nfs.ls.lsst.org
        path: /lsstdata/user/staff/jhome
