serviceAccountName: sqlproxy-butler-int

nameOverride: sqlproxy-butler-int

serviceAccount:
  annotations: {
    iam.gke.io/gcp-service-account: sqlproxy-butler-int@science-platform-dev-7696.iam.gserviceaccount.com
  }

cloudsql:
  nameSuffix: "butler-int"
  ipAddressType: "PUBLIC"
  instanceConnectionName: "science-platform-int-dc5d:us-central1:butler-registry-int-72f9812d"

replicaCount: 1

image:
  repository: gcr.io/cloudsql-docker/gce-proxy
  tag: 1.28.0

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
