replicaCount: 1

config:

  # Use the CSI storage class so that we can use snapshots.
  redis:
    persistence:
      storageClass: "wekafs--sdf-k8s01"

  loglevel: "DEBUG"

  host: "rubin-data-dev.slac.stanford.edu"
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  username_claim: "name"

  oidc:
    clientId: rubin-usdf-staffrsp-dev
    audience: "rubin-usdf-staffrsp-dev"
    loginUrl: "https://dex.slac.stanford.edu/auth"
    tokenUrl: "https://dex.slac.stanford.edu/token"
    issuer: "https://dex.slac.stanford.edu"
    scopes:
    - "openid"
    - "email"
    - "groups"
    - "profile"

  ldap:
    url: ldaps://ldap-unix.slac.stanford.edu:636
    baseDn: dc=slac,dc=stanford,dc=edu
    uidBaseDn: ou=Accounts,dc=slac,dc=stanford,dc=edu
    uidAttr: uidNumber
    groupObjectClass: posixGroup
    groupMemberAttr: memberUid

  # Allow access by GitHub team.
  groupMapping:
    "exec:admin":
      - "unix-admin"
    "exec:notebook":
      - "lsst"
    "exec:portal":
      - "lsst"
    "exec:user":
      - "lsst"
    "read:tap":
      - "lsst"

  initialAdmins:
    - "ytl"
    - "ppascual"

  errorFooter: |
    To report problems or ask for help, please open an issue in the
    <a href="https://github.com/rubin-dp0/Support/issues">GitHub
    rubin-dp0/Support project</a>.

cloudsql:
  enabled: false

