gafaelfawr:

  replicaCount: 2

  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "rubin-data-dev.slac.stanford.edu"
  vaultSecretsPath: "secret/rubin/usdf-staffrsp-dev/gafaelfawr"

  # Use the CSI storage class so that we can use snapshots.
  redis:
    persistence:
      storageClass: "standard-rwo"

  config:

    loglevel: "DEBUG"

    host: "rubin-data-dev.slac.stanford.edu"
    databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

    #github:
    #  clientId: "cb128d0275989031e135"
    oidc:
      clientId: rubin-usdf-staffrsp-dev
      audience: "rubin-usdf-staffrsp-dev"
      loginUrl: "https://dex-dev.slac.stanford.edu/auth"
      tokenUrl: "https://dex-dev.slac.stanford.edu/token"
      issuer: "https://dex-dev.slac.stanford.edu"
      scopes:
      - "openid"
      - "email"
      - "groups"
      - "profile"

    ldap:
      url: ldaps://ldap-unix.slac.stanford.edu:636
      baseDn: ou=Accounts,dc=slac,dc=stanford,dc=edu

    # Allow access by GitHub team.
    groupMapping:
      "exec:admin":
        - "slaclab-rsp-admins"
      "exec:notebook":
        - "slaclab-everyone"
      "exec:portal":
        - "slaclab-everyone"
      "exec:user":
        - "slaclab-everyone"
      "read:tap":
        - "slaclab-everyone"

    initialAdmins:
      - "yee379"
      - "pjpascual"

    errorFooter: |
      To report problems or ask for help, please open an issue in the
      <a href="https://github.com/rubin-dp0/Support/issues">GitHub
      rubin-dp0/Support project</a>.

  cloudsql:
    enabled: false

pull-secret:
  enabled: true
  path: "secret/rubin/usdf-staffrsp-dev/pull-secret"
