redis:
  persistence:
    storageClass: "rook-ceph-block"

config:
  slackAlerts: true
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  github:
    clientId: "49533cbd8a8079730dcf"

  # Support OpenID Connect clients like Chronograf.
  oidcServer:
    enabled: true

  # Allow access by GitHub team.
  groupMapping:
    "admin:provision":
      - "lsst-sqre-square"
    "exec:admin":
      - "lsst-sqre-square"
    "exec:notebook":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
      - "rubin-summit-rsp-access"
    "exec:portal":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
      - "rubin-summit-rsp-access"
    "read:image":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
      - "rubin-summit-rsp-access"
    "read:tap":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
      - "rubin-summit-rsp-access"

  initialAdmins:
    - "afausti"
    - "athornton"
    - "cbanek"
    - "frossie"
    - "jonathansick"
    - "rra"
    - "simonkrughoff"
