gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "rubin-data-dev.slac.stanford.edu"
  vaultSecretsPath: "secret/rubin/rubin-data-dev.slac.stanford.edu/gafaelfawr"

  # Use the CSI storage class so that we can use snapshots.
  redis:
    persistence:
      storageClass: "standard-rwo"

  config:
    host: "rubin-data-dev.slac.stanford.edu"
    databaseUrl: "postgresql://gafaelfawr@localhost/gafaelfawr"

    github:
      clientId: "a39d4b6c7871e4a4bb1f"

    # Allow access by GitHub team.
    groupMapping:
      "exec:admin":
        - "lsst-sqre-square"
      "exec:notebook":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
      "exec:portal":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
      "exec:user":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
      "read:tap":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"

pull-secret:
  enabled: true
  path: "secret/rubin/rubin-data-dev.slac.stanford.edu/pull-secret"
