replicaCount: 2

# Use the CSI storage class so that we can use snapshots.
redis:
  persistence:
    storageClass: "standard-rwo"

config:
  slackAlerts: true

  github:
    clientId: "65b6333a066375091548"

  # Allow access by GitHub team.
  groupMapping:
    "admin:provision":
      - "lsst-sqre-square"
    "exec:admin":
      - "lsst-sqre-square"
    "exec:notebook":
      - "lsst-sqre-square"
      - "lsst-data-management"
      - "lsst-ops"
      - "rubin-dp0-delegates"
      - "rubin-dp0-friends"
    "exec:portal":
      - "lsst-sqre-square"
      - "lsst-data-management"
      - "lsst-ops"
      - "rubin-dp0-delegates"
      - "rubin-dp0-friends"
    "read:image":
      - "lsst-sqre-square"
      - "lsst-data-management"
      - "lsst-ops"
      - "rubin-dp0-delegates"
      - "rubin-dp0-friends"
    "read:tap":
      - "lsst-sqre-square"
      - "lsst-data-management"
      - "lsst-ops"
      - "rubin-dp0-delegates"
      - "rubin-dp0-friends"

  initialAdmins:
    - "afausti"
    - "athornton"
    - "cbanek"
    - "frossie"
    - "jonathansick"
    - "rra"
    - "simonkrughoff"

  errorFooter: |
    To report problems or ask for help, please open an issue in the
    <a href="https://github.com/rubin-dp0/Support/issues">GitHub
    rubin-dp0/Support project</a>.

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-stable-6994:us-central1:science-platform-stable-0c29612b"
  serviceAccount: "gafaelfawr@science-platform-stable-6994.iam.gserviceaccount.com"
