# Reset token storage on every Redis restart.
redis:
  persistence:
    enabled: false

config:
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  # Support OpenID Connect clients like Chronograf.
  oidcServer:
    enabled: true

  github:
    clientId: "65b6333a066375091548"

  # Allow access by GitHub team.
  groupMapping:
    "admin:provision":
      - "lsst-sqre-square"
    "exec:admin":
      - "lsst-sqre-square"
    "exec:notebook":
      - "lsst-sqre-square"
    "exec:portal":
      - "lsst-sqre-square"
    "read:image":
      - "lsst-sqre-square"
    "read:tap":
      - "lsst-sqre-square"

  initialAdmins:
    - "afausti"
    - "athornton"
    - "cbanek"
    - "frossie"
    - "jonathansick"
    - "rra"
    - "simonkrughoff"
