replicaCount: 2

config:

  # Use the CSI storage class so that we can use snapshots.
  redis:
    persistence:
      storageClass: "wekafs--sdf-k8s01"

  loglevel: "DEBUG"

  host: "rubin-data-dev.slac.stanford.edu"
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"


  oidc:
    clientId: rubin-usdf-staffrsp-dev
    audience: "rubin-usdf-staffrsp-dev"
    loginUrl: "https://dex.slac.stanford.edu/auth"
    tokenUrl: "https://dex.slac.stanford.edu/token"
    issuer: "https://dex.slac.stanford.edu"
    scopes:
    - "openid"
    - "email"
    - "groups"
    - "profile"
    usernameClaim: "name"

  ldap:
    url: ldaps://ldap-unix.slac.stanford.edu:636
    #usernameBaseDn: ou=Accounts,dc=slac,dc=stanford,dc=edu
    usernameSearchAttr: uid
    baseDn: dc=slac,dc=stanford,dc=edu
    uidBaseDn: ou=Accounts,dc=slac,dc=stanford,dc=edu
    uidAttr: uidNumber
    groupObjectClass: posixGroup
    groupMemberAttr: memberUid

  # Allow access by GitHub team.
  groupMapping:
    "exec:admin":
      - "unix-admin"
    "exec:notebook":
      - "lsst"
      - lsst-ccs
      - "sf"
      - rubin_users
      - rubin_users-a
      - rubin_users-b
      - rubin_users-c
      - rubin_users-d
      - rubin_users-e
      - rubin_users-f
      - rubin_users-g
      - rubin_users-h
      - rubin_users-i
      - rubin_users-j
      - rubin_users-k
      - rubin_users-l
      - rubin_users-m
      - rubin_users-n
      - rubin_users-o
      - rubin_users-p
      - rubin_users-q
      - rubin_users-r
      - rubin_users-s
      - rubin_users-t
      - rubin_users-u
      - rubin_users-v
      - rubin_users-w
      - rubin_users-x
      - rubin_users-y
      - rubin_users-z
      - rubin_admin_datasets
      - rubin_admin_repos
      - "unix-admin"
    "exec:portal":
      - "lsst"
      - lsst-ccs
      - "sf"
      - rubin_users
      - rubin_users-a
      - rubin_users-b
      - rubin_users-c
      - rubin_users-d
      - rubin_users-e
      - rubin_users-f
      - rubin_users-g
      - rubin_users-h
      - rubin_users-i
      - rubin_users-j
      - rubin_users-k
      - rubin_users-l
      - rubin_users-m
      - rubin_users-n
      - rubin_users-o
      - rubin_users-p
      - rubin_users-q
      - rubin_users-r
      - rubin_users-s
      - rubin_users-t
      - rubin_users-u
      - rubin_users-v
      - rubin_users-w
      - rubin_users-x
      - rubin_users-y
      - rubin_users-z
      - rubin_admin_datasets
      - rubin_admin_repos
      - "unix-admin"
    "exec:user":
      - "lsst"
      - lsst-ccs
      - "sf"
      - rubin_users
      - rubin_users-a
      - rubin_users-b
      - rubin_users-c
      - rubin_users-d
      - rubin_users-e
      - rubin_users-f
      - rubin_users-g
      - rubin_users-h
      - rubin_users-i
      - rubin_users-j
      - rubin_users-k
      - rubin_users-l
      - rubin_users-m
      - rubin_users-n
      - rubin_users-o
      - rubin_users-p
      - rubin_users-q
      - rubin_users-r
      - rubin_users-s
      - rubin_users-t
      - rubin_users-u
      - rubin_users-v
      - rubin_users-w
      - rubin_users-x
      - rubin_users-y
      - rubin_users-z
      - rubin_admin_datasets
      - rubin_admin_repos
      - "unix-admin"
    "read:tap":
      - "lsst"
      - lsst-ccs
      - "sf"
      - rubin_users
      - rubin_users-a
      - rubin_users-b
      - rubin_users-c
      - rubin_users-d
      - rubin_users-e
      - rubin_users-f
      - rubin_users-g
      - rubin_users-h
      - rubin_users-i
      - rubin_users-j
      - rubin_users-k
      - rubin_users-l
      - rubin_users-m
      - rubin_users-n
      - rubin_users-o
      - rubin_users-p
      - rubin_users-q
      - rubin_users-r
      - rubin_users-s
      - rubin_users-t
      - rubin_users-u
      - rubin_users-v
      - rubin_users-w
      - rubin_users-x
      - rubin_users-y
      - rubin_users-z
      - rubin_admin_datasets
      - rubin_admin_repos
      - "unix-admin"

  initialAdmins:
    - "ytl"
    - "ppascual"

  errorFooter: |
    To report problems or ask for help, please open an issue in the
    <a href="https://github.com/rubin-dp0/Support/issues">GitHub
    rubin-dp0/Support project</a>.

cloudsql:
  enabled: false

