apiVersion: v2
name: sasquatch
version: 1.0.0
description: Rubin Observatory's telemetry service.
appVersion: 0.1.0
dependencies:
  - name: strimzi-kafka
    version: 1.0.0
  - name: strimzi-registry-operator
    version: 2.1.0
    repository: https://lsst-sqre.github.io/charts/
  - name: influxdb
    version: 4.12.0
    repository: https://helm.influxdata.com/
  - name: kafka-connect-manager
    version: 1.0.0
  - name: chronograf
    version: 1.2.5
    repository: https://helm.influxdata.com/
  - name: kapacitor
    version: 1.4.6
    repository: https://helm.influxdata.com/
  - name: kafdrop
    version: 1.0.0
