# Default values for Sasquatch.

# -- Override strimzi-kafka configuration.
strimzi-kafka: {}

# -- strimzi-registry-operator configuration.
strimzi-registry-operator:
  clusterName: sasquatch
  clusterNamespace: sasquatch
  operatorNamespace: sasquatch

influxdb:
  # -- InfluxDB image tag.
  image:
    tag: "1.8.10"
  persistence:
    # -- Enable persistent volume claim.
    # By default storageClass is undefined choosing the default provisioner (standard on GKE).
    enabled: true
    # -- Persistent volume size.
    # @default 1Ti for teststand deployments
    size: 1Ti
  # -- Default InfluxDB user, use influxb-user and influxdb-password keys from secret.
  setDefaultUser:
    enabled: true
    user:
      existingSecret: sasquatch
  # -- InfluxDB ingress configuration.
  # @default -- disabled
  ingress:
    enabled: false
    tls: false
    hostname: ""
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    className: "nginx"
    path: /influxdb(/|$)(.*)
  # -- Override InfluxDB configuration.
  # See https://docs.influxdata.com/influxdb/v1.8/administration/config
  config:
    data:
      cache-max-memory-size: 0
      wal-fsync-delay: "100ms"
      trace-logging-enabled: true
    http:
      enabled: true
      flux-enabled: true
      auth-enabled: true
      max-row-limit: 0
    coordinator:
      write-timeout: "1h"
      max-concurrent-queries: 0
      query-timeout: "0s"
      log-queries-after: "15s"
    continuous_queries:
      enabled: false
    logging:
      level: "debug"
  initScripts:
    # -- Enable InfluxDB custom initialization script.
    enabled: false
    # scripts:
    # # -- InfluxDB custom initialization script.
    #   init.iql: |+

# -- Override kafka-connect-manager configuration.
kafka-connect-manager: {}

chronograf:
  # -- Chronograf image tag.
  image:
    repository: "quay.io/influxdb/chronograf"
    tag: 1.9.4
  # -- Chronograf data persistence configuration.
  persistence:
    enabled: true
    size: 100Gi
  # -- Chronograf ingress configuration.
  # @default -- disabled
  ingress:
    enabled: false
    tls: false
    hostname: ""
    className: "nginx"
    path: /chronograf(/|$)
  # -- Chronograf environment variables.
  env:
    HOST_PAGE_DISABLED: true
    BASE_PATH: /chronograf
    CUSTOM_AUTO_REFRESH: "1s=1000"
  # -- Chronograf secrets, expected keys generic_client_id, generic_client_secret and token_secret.
  envFromSecret: "sasquatch"

kapacitor:
  # -- Kapacitor image tag.
  image:
    repository: kapacitor
    tag: 1.6.5
  # -- Chronograf data persistence configuration.
  persistence:
    enabled: true
    size: 100Gi
  # -- InfluxDB connection URL.
  influxURL: http://sasquatch-influxdb.sasquatch:8086
  # -- InfluxDB credentials, use influxdb-user and influxdb-password keys from secret.
  existingSecret: sasquatch
  # -- Kapacitor environment variables.
  envVars:
    KAPACITOR_SLACK_ENABLED: true
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 16Gi
      cpu: 4

global:
  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
