strimzi-kafka:
  kafka:
    storage:
      storageClassName: rook-ceph-block
    externalListener:
      tls:
        enabled: true
      bootstrap:
        loadBalancerIP: "140.252.146.59"
        host: sasquatch-tts-kafka-bootstrap.lsst.codes
      brokers:
        - loadBalancerIP: "140.252.146.46"
          host: sasquatch-tts-kafka-0.lsst.codes
        - loadBalancerIP: "140.252.146.58"
          host: sasquatch-tts-kafka-1.lsst.codes
        - loadBalancerIP: "140.252.146.47"
          host: sasquatch-tts-kafka-2.lsst.codes
  zookeeper:
    storage:
      storageClassName: rook-ceph-block

influxdb:
  persistence:
    storageClass: rook-ceph-block
  # Temporarily enable this ingress to allow access by the EFD client
  # version 0.11.0. Once version 0.12.0 is the default one, this
  # can be removed and we should use tucson-teststand.lsst.codes/influxdb
  # instead.
  ingress:
    enabled: true
    tls: true
    secretName: tls-certs
    hostname: influxdb-tucson-teststand-efd.lsst.codes
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/proxy-body-size: "0m"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Path /;
    path: /

kafka-connect-manager:
  influxdbSink:
    # Based on the kafka producers configuration for the TTS
    # https://github.com/lsst-ts/argocd-csc/blob/main/apps/kafka-producers/values-tucson-teststand.yaml
    connectors:
      auxtel:
        enabled: true
        topicsRegex: ".*ATAOS|.*ATDome|.*ATDomeTrajectory|.*ATHexapod|.*ATPneumatics|.*ATPtg|.*ATMCS"
      maintel:
        enabled: true
        topicsRegex: ".*MTAOS|.*MTDome|.*MTDomeTrajectory|.*MTPtg"
      mtmount:
        enabled: true
        topicsRegex: ".*MTMount"
      comcam:
        enabled: true
        topicsRegex: ".*CCArchiver|.*CCCamera|.*CCHeaderService|.*CCOODS"
      eas:
        enabled: true
        topicsRegex: ".*DIMM|.*DSM|.*WeatherStation"
      latiss:
        enabled: true
        topicsRegex: ".*ATArchiver|.*ATCamera|.*ATHeaderService|.*ATOODS|.*ATSpectrograph"
      m1m3:
        enabled: true
        topicsRegex: ".*MTM1M3"
      m2:
        enabled: true
        topicsRegex: ".*MTHexapod|.*MTM2|.*MTRotator"
      obssys:
        enabled: true
        topicsRegex: ".*GenericCamera|.*Scheduler|.*Script|.*ScriptQueue|.*Watcher"
      ocps:
        enabled: true
        topicsRegex: ".*OCPS"
      test:
        enabled: true
        topicsRegex: ".*Test"
      pmd:
        enabled: true
        topicsRegex: ".*PMD"
      calsys:
        enabled: true
        topicsRegex: ".*ATMonochromator|.*ATWhiteLight|.*CBP|.*Electrometer|.*FiberSpectrograph|.*LinearStage|.*TunableLaser"
      mtaircompressor:
        enabled: true
        topicsRegex: ".*MTAirCompressor"
      authorize:
        enabled: true
        topicsRegex: ".*Authorize"
      mtalignment:
        enabled: true
        topicsRegex: ".*MTAlignment"

kafdrop:
  ingress:
    enabled: true
    hostname: tucson-teststand.lsst.codes

chronograf:
  persistence:
    storageClass: rook-ceph-block
  ingress:
    enabled: true
    hostname: tucson-teststand.lsst.codes
  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://tucson-teststand.lsst.codes/auth/openid/login
    GENERIC_TOKEN_URL: https://tucson-teststand.lsst.codes/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://tucson-teststand.lsst.codes/.well-known/jwks.json
    GENERIC_API_URL: https://tucson-teststand.lsst.codes/auth/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://tucson-teststand.lsst.codes
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/tucson-teststand.json

kapacitor:
  persistence:
    storageClass: rook-ceph-block
