apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tap-schema.fullname" . }}-db
  labels:
    {{- include "tap-schema.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tap-schema.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tap-schema.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: MYSQL_DATABASE
              value: "TAP_SCHEMA"
            - name: MYSQL_USER
              value: "TAP_SCHEMA"
            - name: MYSQL_PASSWORD
              value: "TAP_SCHEMA"
            - name: MYSQL_ROOT_HOST
              value: "%"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - containerPort: 3306
              protocol: "TCP"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      imagePullSecrets:
        - name: "pull-secret"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
