apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "pull-secret"
  labels:
    {{- include "tap-schema.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/pull-secret"
  type: "kubernetes.io/dockerconfigjson"
