apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argocd"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "argocd"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    path: "services/argocd"
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.revision | quote }}
    helm:
      parameters:
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vault_path_prefix | quote }}
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.environment }}.yaml"
