environment: usdfdev
fqdn: usdf-rsp-dev.slac.stanford.edu
vaultPathPrefix: secret/rubin/usdf-rsp-dev
# butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-repos.yaml"
repoURL: https://github.com/slaclab/phalanx.git

alert-stream-broker:
  enabled: false
cachemachine:
  enabled: true
cert-manager:
  enabled: false
datalinker:
  enabled: true
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
hips:
  enabled: false
ingress-nginx:
  enabled: true
mobu:
  enabled: true
moneypenny:
  enabled: true
narrativelog:
  enabled: false
noteburst:
  enabled: false
nublado2:
  enabled: true
obstap:
  enabled: false
plot-navigator:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
sasquatch:
  enabled: true
production-tools:
  enabled: false
semaphore:
  enabled: true
sherlock:
  enabled: false
squareone:
  enabled: true
squash-api:
  enabled: false
strimzi:
  enabled: true
strimzi-registry-operator:
  enabled: false
tap:
  enabled: true
tap-schema:
  enabled: true
telegraf:
  enabled: false
telegraf-ds:
  enabled: false
times-square:
  enabled: false
vault-secrets-operator:
  enabled: true
vo-cutouts:
  enabled: false
