environment: usdfdev
fqdn: rubin-data-dev.slac.stanford.edu
vault_path_prefix: secret/rubin/usdf-staffrsp-dev
#revision: "tickets/DM-28120"

argo:
  enabled: true
alert_stream_broker:
  enabled: false
cachemachine:
  enabled: true
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
chronograf:
  enabled: false
alert_stream_broker:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
#landing_page:
#  enabled: true
#logging:
#  enabled: false
mobu:
  enabled: true
moneypenny:
  enabled: true
ingress_nginx:
  enabled: false
alert_stream_broker:
  enabled: false
nublado:
  enabled: false
nublado2:
  enabled: true
obstap:
  enabled: true
alert_stream_broker:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
#rancher_external_ip_webhook:
#  enabled: false
semaphore:
  enabled: true
squareone:
  enabled: true
strimzi:
  enabled: false
strimzi_registry_operator:
  enabled: false
#squash_api:
#  enabled: false
tap:
  enabled: true
vault_secrets_operator:
  enabled: false
vo_cutouts:
  enabled: false
