{{- if (index .Values "strimzi-registry-operator" "enabled") -}}
apiVersion: v1
kind: Namespace
metadata:
  name: strimzi-registry-operator
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-registry-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: strimzi-registry-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/strimzi-registry-operator
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - values-{{ .Values.environment }}.yaml
{{- end -}}
