{{- if .Values.telegraf.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: telegraf-ds
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf-ds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: telegraf-ds
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/telegraf-ds
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
        - name: "global.enabledServices"
          value: {{ include "enabledServices" . | quote }}
        - name: "global.host"
          value: {{ .Values.fqdn | quote }}
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vaultPathPrefix | quote }}
      valueFiles:
        - values.yaml
        - values-{{ .Values.environment }}.yaml
{{- end -}}
