{{- if .Values.config.createIssuer -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "cert-manager.fullname" . }}
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  path: "{{ required "global.vaultSecretsPath must be set" .Values.global.vaultSecretsPath }}/cert-manager"
  type: Opaque
{{- end }}
