apiVersion: v2
name: cert-manager
version: 1.0.0
description: "Let's Encrypt certificate management"
dependencies:
  - name: cert-manager
    version: v1.9.1
    repository: https://charts.jetstack.io
