cert-manager:
  installCRDs: true
  extraArgs:
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53

pull-secret:
  enabled: true
  path: secret/rubin/data-dev.lsst.cloud/pull-secret
