apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "cachemachine.fullname" . }}-pull
  labels:
    {{- include "cachemachine.labels" . | nindent 4 }}
spec:
  # Reject all inbound and outbound connections to the pods that exist solely
  # to pull Docker images.
  podSelector:
    matchLabels:
      cachemachine: "pull"
  policyTypes:
    - Ingress
    - Egress
