apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}
  labels:
    {{- include "cachemachine.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}
  labels:
    {{- include "cachemachine.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}
  labels:
    {{- include "cachemachine.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cachemachine.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "cachemachine.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}
  labels:
    {{- include "cachemachine.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["create", "delete"]
  - apiGroups: ["apps"]
    resources: ["daemonsets/status"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}
  labels:
    {{- include "cachemachine.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cachemachine.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "cachemachine.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
