apiVersion: v1
kind: Service
metadata:
  name: {{ include "cachemachine.fullname" . }}
  labels:
    {{- include "cachemachine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: "http"
      protocol: "TCP"
  selector:
    {{- include "cachemachine.selectorLabels" . | nindent 4 }}
