semaphore:
  config:
    phalanx_env: "usdfdev"
    github_app_id: "131502"
    enable_github_app: "True"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: "rubin-data-dev.slac.stanford.edu"
        paths:
          - path: "/semaphore"
            pathType: Prefix
  imagePullSecrets:
    - name: "pull-secret"
  vaultSecretsPath: "secret/rubin/usdf-staffrsp-dev/semaphore"

pull-secret:
  enabled: true
  path: secret/rubin/usdf-staffrsp-dev/pull-secret
