strimzi-kafka: {}

influxdb:
  ingress:
    enabled: true
    hostname: usdf-rsp.slac.stanford.edu

kafka-connect-manager:
  influxdbSink:
    influxdb-sink:
      enabled: true
      tasksMax: 10

kafdrop:
  ingress:
    enabled: true
    hostname: usdf-rsp.slac.stanford.edu

chronograf:
  ingress:
    enabled: true
    hostname: usdf-rsp.slac.stanford.edu

  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://usdf-rsp.slac.stanford.edu/auth/openid/login
    GENERIC_TOKEN_URL: https://usdf-rsp.slac.stanford.edu/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://usdf-rsp.slac.stanford.edu/.well-known/jwks.json
    GENERIC_API_URL: https://usdf-rsp.slac.stanford.edu/auth/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://usdf-rsp.slac.stanford.edu/
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/usdfprod.json
