## Ingress configuration
## https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
ingress-nginx:
  controller:
    config:
      compute-full-forwarded-for: "true"
      large-client-header-buffers: "4 64k"
      proxy-body-size: "100m"
      proxy-buffer-size: "64k"
      ssl-redirect: "true"
      use-forwarded-headers: "true"
    service:
      externalTrafficPolicy: Local
    podLabels:
      gafaelfawr.lsst.io/ingress: "true"
      hub.jupyter.org/network-access-proxy-http: "true"
    metrics:
      enabled: true

vaultCertificate:
  # -- Whether to store ingress TLS certificate via
  # vault-secrets-operator.  Typically "squareone" owns it instead in an
  # RSP.
  enabled: false

# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
