apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sqlproxy.fullname" . }}
  labels:
    {{- include "sqlproxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

