apiVersion: v2
name: noteburst
version: 1.0.0
appVersion: "0.5.0"
description: Noteburst is a notebook execution service for the Rubin Science Platform.
type: application
home: https://noteburst.lsst.io/
sources:
  - https://github.com/lsst-sqre/noteburst
maintainers:
  - name: jonathansick
    url: https://github.com/jonathansick

# Additional charts that this chart uses
dependencies:
  - name: redis
    version: 17.1.4
    repository: https://charts.bitnami.com/bitnami
