cachemachine:
  host: "rubin-data-dev.slac.stanford.edu"

  ingress:
    enabled: true
    hosts:
      - host: rubin-data-dev.slac.stanford.edu
        paths: ["/cachemachine"]
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://rubin-data-dev.slac.stanford.edu/login"
      nginx.ingress.kubernetes.io/auth-url: "https://rubin-data-dev.slac.stanford.edu/auth?scope=exec:admin"

  imagePullSecrets:
    - name: "cachemachine-secret"

  vaultSecretsPath: "secret/rubin/usdf-staffrsp-dev/pull-secret"

  autostart:
    jupyter: |
      {
        "name": "jupyter",
        "labels": {},
        "repomen": [
          {
            "type": "RubinRepoMan",
            "registry_url": "registry.hub.docker.com",
            "repo": "lsstsqre/sciplat-lab",
            "recommended_tag": "recommended",
            "num_releases": 1,
            "num_weeklies": 2,
            "num_dailies": 3
          },
          {
            "type": "SimpleRepoMan",
            "images": [
              {
                "image_url": "registry.hub.docker.com/lsstsqre/sciplat-lab:w_2021_49",
                "name": "Weekly 2021_49"
              }
            ]
          }
        ]
      }
