nublado2:
  jupyterhub:
    debug:
      enabled: true
    hub:
      resources:
        requests:
          cpu: "1"
          memory: 3Gi
    ingress:
      hosts: ["rubin-data-dev.slac.stanford.edu"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://rubin-data-dev.slac.stanford.edu/login"
        nginx.ingress.kubernetes.io/auth-url: "https://rubin-data-dev.slac.stanford.edu/auth?scope=exec:notebook&notebook=true"

  config:
    base_url: "https://rubin-data-dev.slac.stanford.edu"
    butler_secret_path: "secret/rubin/usdf-staffrsp-dev/butler-secret"
    pull_secret_path: "secret/rubin/usdf-staffrsp-dev/pull-secret"

    lab_environment:
      PGPASSFILE: "/opt/lsst/software/jupyterlab/butler-secret/postgres-credentials.txt"
      AWS_SHARED_CREDENTIALS_FILE: "/opt/lsst/software/jupyterlab/butler-secret/aws-credentials.ini"
      S3_ENDPOINT_URL: "https://storage.googleapis.com"
      AUTO_REPO_URLS: https://github.com/lsst-sqre/system-test,https://github.com/rubin-dp0/tutorial-notebooks
      AUTO_REPO_BRANCH: prod
      AUTO_REPO_SPECS: https://github.com/lsst-sqre/system-test@prod,https://github.com/rubin-dp0/tutorial-notebooks@prod

    volumes:
      - name: datasets
        hostPath:
          path: /data
      - name: home
        hostPath:
          path: /tmp
      - name: project
        hostPath:
          path: /tmp 
      - name: scratch
        hostPath:
          path: /tmp
    volume_mounts:
      - name: datasets
        mountPath: /datasets
      - name: home
        mountPath: /home
      - name: project
        mountPath: /project
      - name: scratch
        mountPath: /scratch

      - apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: "{{ user }}-serviceaccount"
          namespace: "{{ user_namespace }}"
        imagePullSecrets:
        - name: pull-secret
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: "{{ user }}-role"
          namespace: "{{ user_namespace }}"
        rules:
        # cf https://kubernetes.dask.org/en/latest/kubecluster.html
          - apiGroups: [""]
            resources: ["pods", "services"]
            verbs: ["create", "delete", "get", "list", "watch"]
          - apiGroups: [""]
            resources: ["pods/log"]
            verbs: ["get","list"]
          - apiGroups: ["policy"]
            resources: ["poddisruptionbudgets"]
            verbs: ["create", "delete", "get", "list", "watch"]
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: "{{ user }}-rolebinding"
          namespace: "{{ user_namespace }}"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: "{{ user }}-role"
        subjects:
          - kind: ServiceAccount
            name: "{{ user }}-serviceaccount"
            namespace: "{{ user_namespace }}"
      - apiVersion: ricoberger.de/v1alpha1
        kind: VaultSecret
        metadata:
          name: butler-secret
          namespace: "{{ user_namespace }}"
        spec:
          path: "{{ butler_secret_path }}"
          type: Opaque
      - apiVersion: ricoberger.de/v1alpha1
        kind: VaultSecret
        metadata:
          name: pull-secret
          namespace: "{{ user_namespace }}"
        spec:
          path: "{{ pull_secret_path }}"
          type: kubernetes.io/dockerconfigjson


  vault_secret_path: "secret/rubin/rubin-data-dev.slac.stanford.edu/nublado2"
  # gafaelfawr_secret_path: "secret/rubin/rubin-data-dev.slac.stanford.edu/gafaelfawr"

pull-secret:
  enabled: true
  path: "secret/rubin/usdf-staffrsp-dev/pull-secret"
