nublado2:
  jupyterhub:
    debug:
      enabled: true

    ingress:
      hosts: ["rubin-data-dev.slac.stanford.edu"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://rubin-data-dev.slac.stanford.edu/login"
        nginx.ingress.kubernetes.io/auth-url: "https://rubin-data-dev.slac.stanford.edu/auth?scope=exec:notebook&notebook=true"

    hub:
      baseUrl: '/nb'

  config:
    base_url: "https://rubin-data-dev.slac.stanford.edu"
    volumes:
      - name: datasets
        hostPath:
          path: /share1/datasets
      - name: home
        hostPath:
          path: /share1/home
      - name: project
        hostPath:
          path: /share1/project
      - name: scratch
        hostPath:
          path: /share1/scratch
    volume_mounts:
      - name: datasets
        mountPath: /datasets
      - name: home
        mountPath: /home
      - name: project
        mountPath: /project
      - name: scratch
        mountPath: /scratch

  vault_secret_path: "secret/rubin/rubin-data-dev.slac.stanford.edu/nublado2"
  gafaelfawr_secret_path: "secret/rubin/rubin-data-dev.slac.stanford.edu/gafaelfawr"
