apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: sasquatch
  namespace: sasquatch
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/sasquatch"
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/pull-secret"
  type: kubernetes.io/dockerconfigjson
---
# tls-certs secret is here only to enable influxdb-tucson-teststand-efd.lsst.codes
# and should be removed when that's gone.
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: tls-certs
  namespace: sasquatch
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/efd/tls-certs"
  type: Opaque
