[project]
title = "Phalanx"
copyright = "2020-2022 Association of Universities for Research in Astronomy, Inc. (AURA)"
base_url = "https://phalanx.lsst.io"
github_url = "https://github.com/lsst-sqre/phalanx"
github_default_branch = "main"
version = "Current"

[sphinx]
rst_epilog_file = "_rst_epilog.rst"
extensions = [
  "sphinx_diagrams",
  "sphinx_jinja",
  "phalanx.docs.crossref",
]

[sphinx.linkcheck]
ignore = [
    '^http://localhost',
    '^http(s)*://ls.st',
    '^https://tucson-teststand.lsst.codes',
    '^https://summit-lsp.lsst.codes',
    '^https://minikube.lsst.codes',
    '^https://base-lsp.lsst.codes',
    '^https://data-dev.lsst.cloud',
    '^https://data-int.lsst.cloud',
    '^https://data.lsst.cloud',
    '^https://data-dev.lsst.eu',
    '^https://rsp.lsst.ac.uk',
    '^https://roundtable-dev.lsst.cloud',
    '^https://roundtable.lsst.cloud',
    '^https://usdf-rsp.slac.stanford.edu',
    '^https://usdf-rsp-dev.slac.stanford.edu',
    '^https://github.com/lsst-sqre/phalanx/blob/main/applications/strimzi/values.yaml',
    '^https://github.com/orgs/',
]
