{{- if .Values.ingress.enabled -}}
{{- $fullName := include "times-square.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "times-square.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.gafaelfawrAuthQuery }}
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Token
    nginx.ingress.kubernetes.io/auth-signin: "{{ .Values.global.baseUrl }}/login"
    nginx.ingress.kubernetes.io/auth-url: "{{ .Values.global.baseUrl }}/auth?{{ .Values.ingress.gafaelfawrAuthQuery }}"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ required "global.host must be set" .Values.global.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ default "Prefix" .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
