# Use the CSI storage class so that we can use snapshots.
redis:
  persistence:
    storageClass: "standard-rwo"

cloudsql:
  enabled: true
  instanceConnectionName: "roundtable-prod-f6fd:us-central1:roundtable-prod-f119ac3d"
  serviceAccount: "gafaelfawr@roundtable-prod-f6fd.iam.gserviceaccount.com"

config:
  slackAlerts: false

  github:
    clientId: "8ab507cd4b023d77a216"

  # Support OpenID Connect clients like Chronograf.
  oidcServer:
    enabled: false

  groupMapping:
    "exec:admin":
      - github:
          organization: "lsst-sqre"
          team: "square"

  initialAdmins:
    - "afausti"
    - "athornton"
    - "cbanek"
    - "frossie"
    - "jonathansick"
    - "rra"

  errorFooter: |
    To report problems or ask for help, contact #dm-square on the LSSTC Slack.
