apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "datalinker.fullname" . }}-anonymous
  labels:
    {{- include "datalinker.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: "nginx"
  rules:
    - host: {{ required "global.host must be set" .Values.global.host | quote }}
      http:
        paths:
          - path: "/api/hips/list"
            pathType: "Exact"
            backend:
              service:
                name: {{ include "datalinker.fullname" . }}
                port:
                  number: 8080
